# Generated by Django 5.1.1 on 2024-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
